Newsweek Replica Using Bootstrap
mcervantes71/Newsweek_Clone pull request #2
Opened 2020-04-30 00:23 UTC by mcervantes71

* use semantic HTML
 * use Bootstrap CSS classes wherever it is possible
 * HTML and CSS validators

2020-04-30 00:47 UTC, mikenath223 commented
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

2020-04-30 00:57 UTC, mikenath223 requested changes
### Hi @mcervantes71  👋

You've done really well on this project in terms of the frontend structure and layout of the webpage.🚀

However, there are just a few issues that need to be fixed before proceeding:

- [x] Required - Kindly enable stickler on your repo.

- [x] Required - In addition, consider removing the `!important` tag that exists on your CSS codebase. We generally want to avoid CSS bad practices refer to this ([article for support ](https://speckyboy.com/good-bad-css-practices)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/section/css_bad_practices_requirement.png) from Pathwright).

- [x] Required - Also kindly remove the inline styles that exist in your HTML code, refer also to the article mentioned above👆

Kindly fix these issues and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

2020-04-30 00:59 UTC, mikenath223 commented on css/style.css
> +  background-color: #f4f5f7 !important;
Please remove this `!important` tag as well as other `!important` tags that exist in your CSS code.

2020-04-30 01:01 UTC, mikenath223 commented on index.html
> +                            <div class="megazine_article_img" style="background-image: url('../img/megazine8.jpg')"></div>
Kindly remove the inline styling that exists here and other inline styles also.

2020-04-30 01:38 UTC, mcervantes71 commented on css/style.css
> +  background-color: #f4f5f7 !important;
Stickler is enable.
What could be the problem ??

2020-04-30 01:47 UTC, mcervantes71 commented
☑️ Enable stickler in the repository. 👌 
☑️ Refactor the CSS file to remove the !important tags that existed 💪 
☑️ Refactor inline styles that exist in your HTML ✍️

2020-04-30 02:31 UTC, uryelah commented
Hello **Martin Cervantes Palomo**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all great job with your attention to detail, it's really nice how you added the navbar search detail on desktop screens and the text over the images🌟**

There are a couple of issues you need to fix before going to the next project, remember this project needs to be extra closer to the original since Bootstrap is already taking care of the responsiveness and most of the positioning, so keep calm and code on 💪 

---------     

## Required Changes 🏗 👷‍♀ 

- [ ] Before the 'In the Magazine' section there should be no extra spaces from the above sections. This is easily fixable by setting a max-height together with overflow scroll or even a position sticky if you want a challenge. 
Compare the space above the section in your clone and in the original project:

![Screenshot_2020-04-29 Newsweek - News, Analysis, Politics, Business, Technology(1)](https://user-images.githubusercontent.com/16193212/80665734-a8bab500-8a70-11ea-8e51-0e98cc160e6b.png)
![Screenshot_2020-04-29 Newsweek(4)](https://user-images.githubusercontent.com/16193212/80665735-a9ebe200-8a70-11ea-88ba-453047e0b85d.png)

----

- [ ] The 'In the Magazine' first article image is taller than the following ones. Compare below how your clone looks and how it looks in the original and make it look the same:
![Screenshot_2020-04-29 Newsweek - News, Analysis, Politics, Business, Technology](https://user-images.githubusercontent.com/16193212/80665776-c5ef8380-8a70-11ea-8fbb-a9cb12f387a2.png)
![Screenshot_2020-04-29 Newsweek(3)](https://user-images.githubusercontent.com/16193212/80665780-c6881a00-8a70-11ea-94c4-e99735dc3dfe.png)

---

- [ ] Mind the font-weight of the section titles, 'World', 'US', etc, they should be bolder. Tip: you can use Bootstrap to change text weight too.

- [ ] Make sure your navbar if fixed at the top of the page, it should be visible when scrolling down.

- [ ] Remember to keep using semantic HTML. Use `section` tags for sections and `article` tags for articles. You can [read this if you need a refresher on semantic HTML.](https://www.w3schools.com/html/html5_semantic_elements.asp)

----

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-04-30 21:28 UTC, mcervantes71 commented
✔️  Position sticky to reduce extra space before magazine section
✔️ Magazine' first article image is taller than the following ones
✔️ Change font-weight using bootstrap class (title, categories, title section, etc)
✔️ Make navbar fixed

2020-05-01 01:21 UTC, trekab commented
# Project Approved! :ok_hand:
Well done, @mcervantes71! __Let's get this merged.__ :tada:

_Goodluck with your next projects and happy coding!_

2020-05-01 14:01 UTC, merged